### ISSUE TITLE
Properly handle `x` values in Excelreader for all data types

### ISSUE THREAD

**Issue by mradamcox** [azerbini/eamena_dev#50]
### User Story
Currently, excelreader validation fails on date values that are recorded as `x`. These values *are* valid, they just need to be skipped and interpreted as empty. In fact, for nodes of any business table type, `x` just means "empty", not only for concept data types, which was the assumption in the latest revision of the validation code.

This change also needs to also be reflected in the .arches writing commands.

**Comment by mradamcox** [comment]
This should be solved now and can be tested in the published al ula instance.

**Comment by azerbini** [comment]
Actually @mradamcox , this is still not working
<img width="1051" alt="screen shot 2018-09-26 at 09 36 31" src="https://user-images.githubusercontent.com/19243127/46061545-b8289c80-c16f-11e8-88dc-523d52f19419.png">

**Comment by mradamcox** [comment]
oh, I see what's going on now, the values aren't properly split during this validation operation. I'll push a fix momentarily.

**Comment by mradamcox** [comment]
https://github.com/azerbini/eamena_dev/commit/b89a80bd9a33ec373849d3c1a6749cb47fff3420 fixes this.
